### PR TITLE
Add dependabot configuration

### PR DESCRIPTION
**Pull request by pjonsson**
This adds configuration for getting
automatic pull requests for github
actions and golang.

https://docs.github.com/en/code-security/dependabot

### CODE REVIEW

**Comment by MShekow** [comment]
Looks good. I'm not sure whether I'll have much time, though, to merge all those "security issues" it will find...

**Comment by pjonsson** [comment]
The reason I came here was because a registry scanner suddenly flagged our docker images with two high vulnerabilities. The first thing I did was to update the dependencies for directory-checksum, but Dependabot does not sleep or make mistakes, so it seemed like a better choice to automate the task.

I don't know go, but I pulled some development image for 1.19, updated the afero version to the latest release, and ran go build/go test like the README here suggests, and the test suite passed.

I realize you don't control afero, but it would be great if you accept the PR from Dependabot to get the latest afero when it comes, since that removes one security vulnerability in text that is classified as high by vulnerability scanners.

And thank you for merging this!

**Comment by MShekow** [comment]
Thanks for providing your use case / background info. I really do appreciate your PR, and I also love tools like Renovate Bot or Dependabot, so I'll try my best to merge the PRs. I remember having had issues with afero already back then when I was actively working on directory-checksum, but something with a downstream dependency where I'd need to wait for afero to fix it. These problems may have been fixed by now.

There are other build-related problems now anyways which I need to fix first.

**Comment by MShekow** [comment]
@pjonsson I fixed everything I can, see https://github.com/MShekow/directory-checksum/releases/tag/v1.4.1

**Pull request merged**
